### PR TITLE
Add `safeApprove` to `TransferHelper`

### PR DESCRIPTION
**Pull request by Sabnock01**

### CODE REVIEW

**Review by alcueca — COMMENTED** [review]
Just do
```
    /// @notice Approves token transfers from msg.sender for a spender
    /// @dev Errors with the underlying revert message if transfer fails
    /// @param token The contract address of the token which will be approved
    /// @param spender The approved spender
    /// @param value The value of the allowance
    function safeApprove(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        (bool success, bytes memory data) = address(token).call(abi.encodeWithSelector(IERC20.approve.selector, spender, value));
        if (!(success && (data.length == 0 || abi.decode(data, (bool))))) revert(RevertMsgExtractor.getRevertMsg(data));
    }
 ```

**Comment by alcueca** [comment]
We honestly should call these methods `ramTransfer` instead of `safeTransfer` lol.

**Comment by Sabnock01** [comment]
Ok all of this is extremely helpful. I made it way more complicated than necessary.

**Review by alcueca — APPROVED** [review]
Lovely

**Pull request merged**
