### PR TITLE
feat: add link of ebrake audit to readme

### PR DESCRIPTION
**Pull request by devtooligan**
This pr is for discussion of the [EBrake security review](https://hackmd.io/@devtooligan/YieldEmergencyBrakeSecurityReview2022-10-11) and serves as an interim forum for discussion about the review before adding "developer response" to the report and finalizing it.

### CODE REVIEW

**Comment by alcueca** [comment]
With regards to the [permissions not being set according to the comments](https://hackmd.io/@devtooligan/YieldEmergencyBrakeSecurityReview2022-10-11#1-Permissions-on-currently-deployed-contracts-don%E2%80%99t-follow-security-procedures-MEDIUM) in the EmergencyBrake, we should fix the comments first, and then the permissions afterwards.

The comments consider an advanced permissioning case with `planners` and `executors` and warn about the risks of collusion. A more common permissioning configuration is having a single `governor` that has all permissions. This includes `execute` but this permission should be used only on emergencies.

`0xd659565b84BcfcB23B02ee13E46CB51429F4558A` is the Yield Multisig and requires full access, most importantly `execute` and `restore` so that it can act on emergencies.

The Yield Timelock requires `plan` and `cancel`, so that it can configure the EmergencyBrake in a controlled manner.

Developers require `execute`, but not `restore` so that a rogue developer can do no more harm than temporarily pausing contracts.

**Comment by alcueca** [comment]
On the use of `delete`, with the **new** implementation, what would be the real risk of not deleting the mapping? In which scenario could we delete a plan, then create a new plan, and have the second plan reuse data from the first plan?

**Comment by alcueca** [comment]
All the other findings are valid, as I see it.

@hashedMae, I don't know what happened on commit [9d48d4c](https://github.com/yieldprotocol/yield-utils-v2/pull/54/commits/9d48d4c0ae1d9bae6d00655133104316aa73f7fa). In general, it's best not to commit to branches that are under audit. I'd suggest reverting that commit.

Fixes to the contracts as a result of the audit should be in their own branch, so that they can be audited in turn. One of the activities that are most likely to introduce a bug are precisely fixes in response to an audit. We made big mistakes like that in the past.

Once [9d48d4c](https://github.com/yieldprotocol/yield-utils-v2/pull/54/commits/9d48d4c0ae1d9bae6d00655133104316aa73f7fa) is reverted, please act on the audit findings. I would suggest working on the struct refactor first, and once we are happy with that one we merge it into [your branch](https://github.com/yieldprotocol/yield-utils-v2/tree/472-wrap-or-refactor-ebrake) and fix all the other suggestions on a fresh branch.

**Comment by hashedMae** [comment]
> @hashedMae, I don't know what happened on commit [9d48d4c](https://github.com/yieldprotocol/yield-utils-v2/pull/54/commits/9d48d4c0ae1d9bae6d00655133104316aa73f7fa). In general, it's best not to commit to branches that are under audit. I'd suggest reverting that commit.

That was me adding back the old ebrake contract and starting on the scripting to retrieve the current plans on mainnet. I can revert and create a new branch as that's part of the governance part? 

I'll keep in mind not to touch a branch once it's been submitted for audit from now on.

**Review by alcueca — APPROVED** [review]

**Comment by alcueca** [comment]
A whole new EmergencyBrake is out, I'm merging this and waiting for a new audit.

**Pull request merged**
